Having the latest version of Python 3

I have created the mongodb atlas clound database wedeeye -> user collection 

https://cloud.mongodb.com/v2/5cce857d014b76119869c0e9#metrics/replicaSet/5cce86de04e3af1de23b3301/explorer/test/users/find

with latest version of pip installed 

python37 -m pip install dnspython
for allowing dns configuration and this errors occurs even though the module is never used in the program


pip install Flask-PyMongo
pip install Flask


pip install virtualenv
virtualenv -p python venv
venv\Scripts\activate

with the virtual environment running run the program in pyton 

(venv) C:\Python37>

python37 clean.py

the flask would be up and running.


we can start using the endpoint points/ routes for specific n related actions associated with the same


Just starting using the test point for respective actions 



